apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
  labels:
    release: monitoring
spec:
  route:
    repeatInterval: 30m
    receiver: 'null'
    routes:
    - matchers:
      - name: alertname
        value: HighCpuUsage
      receiver: 'send-email'
    - matchers:
      - name: alertname
        value: PodRestart
      receiver: 'send-email'
      repeatInterval: 5m
  receivers:
  - name: 'send-email'
    emailConfigs:
    - to: krishnarrathore19@gmail.com
      from: krishnarrathore19@gmail.com
      sendResolved: false
      smarthost: smtp.gmail.com:587
      authUsername: krishnarrathore19@gmail.com
      authIdentity: krishnarrathore19@gmail.com
      authPassword:
        name: mail-pass
        key: gmail-pass
  - name: 'null'
